// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bamrsqyrwqutqtptekmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhbXJzcXlyd3F1dHF0cHRla214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDQ2NTEsImV4cCI6MjA2NjAyMDY1MX0.0sXQn_ikBQ6S45KfE8CslNgTr-lHVYFw6zHccgifTc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);